FROM node:15-alpine3.13

EXPOSE 8080

RUN mkdir -p /app/public /app/src
WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

ENV PORT=8080

CMD ["npm", "run", "dev"]
