# stage 1
FROM node:15-alpine3.13 as build


RUN mkdir -p /app/public /app/src
WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

ENV NODE_ENV=production

COPY . .

RUN ["npm", "run", "build"]

# final image
FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]