FROM node:15-alpine3.13

EXPOSE 3000

RUN mkdir -p /app/config /app/src
WORKDIR /app

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

RUN npm install

ENV PORT=3000
ENV NODE_ENV=development

CMD ["npm", "run", "dev"]